version: 2

sources:
  - name: raw                       # alias en DBT para tu dataset gz_raw_data
    database: new-project-lewagon   # tu GCP Project ID real
    schema: gz_raw_data             # tu dataset en BigQuery
    tables:
      - name: sales                 # lo que usarás en {{ source('raw','sales') }}
        identifier: raw_gz_sales    # nombre real en BigQuery
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
